### ISSUE TITLE
Heart rate on Ticwatch

### ISSUE THREAD

**Issue by heraldb** [fridgecow/smartalarm#1]
Hi Tom,
Thanks for Smart Alarm. Nice that, apart from seeing a graph, it is possible to export the recorded data in csv format. However, on Ticwatch the heart rate is missing (well, it's "0.0"), probably it is not recorded (I did not see any light at the back of the watch). I checked the settings, but "Record Heart Rate" is on. It's the same for Ticwatch S and Ticwatch E.
Any idea what the cause could be?
Thanks,
Herald

**Comment by fridgecow** [comment]
Interesting. Do you see the heart rate on the watch? It appears as a red line like in [this screenshot](https://github.com/fridgecow/smartalarm/blob/master/screenshots/device-2017-12-30-122852.png?raw=true)

If not, then it's definitely not being recorded by the watch. Could you please go into (system-wide) Settings -> Apps -> Smart Alarm -> Permissions and check that "Sensors" or "Body Sensors" is enabled? If it's disabled I'll ensure it gets enabled on future releases.

Thank you!

**Comment by heraldb** [comment]
The red line was missing.
When looking at permissions for the Smart Alarm app, the permission for sensors was indeed disabled. I switched it on and indeed, right after starting a recording, the lights of the heart rate sensor lighted up and after stopping the recording, the red line was visible. 
Thanks a lot, this solved it.

**Comment by fridgecow** [comment]
It certainly solved the symptom! I'm glad it's working now :)
