### ISSUE TITLE
Can't download to phone

### ISSUE THREAD

**Issue by avi12** [fridgecow/smartalarm#16]
Even though the app's Play Store page claims that it's available for Android 7.0+, it's not available for my Samsung Galaxy S9+ running Android 9.0.
![Screenshot_20190801-001538_Google Play Store](https://user-images.githubusercontent.com/6422804/62248774-98967c00-b3f1-11e9-8b65-9e85fe64598d.jpg)

**Comment by fridgecow** [comment]
The app is a standalone smartwatch app. There is no phone component.

You have to install the app from the play store on your watch, or wirelessly from the computer.
