### ISSUE TITLE
MY ( REM ) ESTIMATED IS (0)

### ISSUE THREAD

**Issue by LBLUE01** [fridgecow/smartalarm#24]
THIS IS MY FIRST TIME USING THIS APP. WHY DOES MY RAPID EYE MOVEMENT SAY ( 0) ESTIMATED

**Comment by fridgecow** [comment]
It's just an estimate, you can read more about the algorithm used on the wiki (or from the source code): https://github.com/fridgecow/smartalarm/wiki/Sleep-Detection

There's also a remediation step you may be able to take: https://github.com/fridgecow/smartalarm/wiki/Help,-my-analysis-is-bad!
