### ISSUE TITLE
Does not export data to email

### ISSUE THREAD

**Issue by acarrizosa** [fridgecow/smartalarm#25]
There seems to be a problem with the server. Application always returns error:null. Email summaries are not received.

**Comment by Alvo-239** [comment]
This problem occurs in the past serval times, but there were no solution from the developer, only the notice, that you can use your own server.

**Comment by RussellNS** [comment]
> This problem occurs in the past serval times, but there were no solution from the developer, only the notice, that you can use your own server.

Any pointers as to how we can use our own server?  I'm familiar with setting up apps to send emails to SMTP, but the only configuration in the Smart Alarm app is a single HTTPS address.

**Comment by fridgecow** [comment]
I'm sorry about this issue. The server occasionally goes down and it takes me a while to get round to restarting it - hopefully it should be working now. I don't really have the time or energy to maintain this project any more.

For setting up your own instance of the server, instructions are here: https://github.com/fridgecow/smartalarm-server
